### ISSUE TITLE
Install fails because of missing VERSION file

### ISSUE THREAD

**Issue by jonathaneunice** [nod/databag#2]
```
Mac ~$ sudo pip install -U databag
Downloading/unpacking databag
  Running setup.py egg_info for package databag
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/private/tmp/pip-build-root/databag/setup.py", line 5, in <module>
        VERSION = open('VERSION').read().lstrip('version: ').rstrip('\n')
    IOError: [Errno 2] No such file or directory: 'VERSION'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/tmp/pip-build-root/databag/setup.py", line 5, in <module>

    VERSION = open('VERSION').read().lstrip('version: ').rstrip('\n')

IOError: [Errno 2] No such file or directory: 'VERSION'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip-build-root/databag
Storing complete log in /Users/jeunice/Library/Logs/pip.log
```

**Comment by nod** [comment]
oops.  I apparently fixed this years ago and didn't close this ticket.  That's poor code hygiene on my part.

Closing.  Just pushed a new version of databag for python3.
